# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'MyMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '9.0'
  use_frameworks!
  

  # Pods for MyMap
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'

  target 'MyMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
